name: defend_your_flame
description: Defend your castles flame from the enemy
publish_to: 'none'
version: 0.12.2+1 # +1 since we haven't actually published this yet

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flame: ^1.17.0
  scoped_model: ^2.0.0
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/mobs/skeleton/
    - assets/images/mobs/strong_skeleton/
    - assets/images/mobs/slime/
    - assets/images/mobs/mage/
    - assets/images/environment/
    - assets/images/environment/rocks/
    - assets/images/masonry/
    - assets/images/hud/
    - assets/images/flames/purple/loops/
    - assets/images/flames/blue/loops/

  fonts:
    - family: Metropolis
      fonts:
      - asset: assets/fonts/Metropolis-Bold.otf
        weight: 800
      - asset: assets/fonts/Metropolis-Regular.otf
      - asset: assets/fonts/Metropolis-Light.otf
        weight: 300
      - asset: assets/fonts/Metropolis-RegularItalic.otf
        style: italic
    - family: ThaleahFat
      fonts:
        - asset: assets/fonts/ThaleahFat.ttf
    - family: prstart
      fonts:
        - asset: assets/fonts/prstart.ttf

