name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /defend_your_flame/
          webRenderer: html # I'd prefer canvaskit, but this causes awful performance in firefox, see: https://github.com/flutter/flutter/issues/129733