name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: anleac/flutter-gh-pages@v0.3
        with:
          baseHref: /defend_your_flame/
          webRenderer: both
